### ISSUE TITLE
Formatting last_changed

### ISSUE THREAD

**Issue by tonyp** [MizterB/lovelace-secondaryinfo-entity-row#2]
Hello,

is it possible to format the last_changed attribute?
It seems like functions like as_timestamp() or strptime() won't get parsed properly.

I guess creating a new template sensor would work, just wanted to check if there's another possible solution.

**Comment by MizterB** [comment]
This may be possible in the future.  I have suggested that [card-tools](https://github.com/thomasloven/lovelace-card-tools) implement the ability for templates to reference functions that could execute arbitrary code.  No commitments on when/if that will be possible, but it is being considered.

**Comment by GoNzCiD** [comment]
I solve it with this:
```YAML
card:
  entities:
    - entity: switch.myswitch
      secondary_info: '${ new Date(states[''switch.myswitch''].last_updated).toLocaleString(''es-ES'') }'
      type: 'custom:secondaryinfo-entity-row'
  show_header_toggle: false
  title: ⚙️ My Title
  type: 'custom:hui-entities-card'
type: 'custom:config-template-card'
```

**Comment by tyjtyj** [comment]
@GoNzCiD it dint work for me ... need some additional JS ?

```
      card:
        entities:
          - entity: input_boolean.vr_tracking_anyone
            secondary_info: '${ new Date(states[''input_boolean.vr_tracking_anyone''].last_updated).toLocaleString(''es-ES'') }'
            type: 'custom:secondaryinfo-entity-row'
```
